<?php

namespace App\Controllers;

use App\Models\TerjualM;

class Terjual extends BaseController
{
    protected $terjualm;
    function __construct()
    {
        $this->terjualm = new TerjualM();
    }
    public function index()
    {
        $this->data = array('title' => 'Terjual | Admin', 'breadcome' => 'Terjual', 'url' => 'terjual/', 'm_terjual' => 'active', 'session' => $this->session);

        echo view('App\Views\terjual\terjual_list', $this->data);
    }

    public function ajax_request()
    {
        $list = $this->terjualm->get_datatables();
        $data = array();
        $no = isset($_GET['offset']) ? $_GET['offset'] + 1 : 1;
        foreach ($list as $rows) {
            $row = array();
            $row['id'] = $rows->id;
            $row['nomor'] = $no++;
            $row['id_barang'] = $rows->id_barang;
            $row['jumlah'] = $rows->jumlah;
            $data[] = $row;
        }
        $output = array(
            "total" => $this->terjualm->total(),
            "totalNotFiltered" => $this->terjualm->countAllResults(),
            "rows" => $data,
        );
        echo json_encode($output);
    }
    public function create()
    {
        $this->data = array('action' => 'insert', 'btn' => '<i class="fas fa-save"></i> Save');
        $num_of_row = $this->request->getPost('num_of_row');
        for ($x = 1; $x <= $num_of_row; $x++) {
            $data['nama'] = 'Data ' . $x;
            $this->data['form_input'][] = view('App\Views\terjual\form_input', $data);
        }
        $status['html']         = view('App\Views\terjual\form_modal', $this->data);
        $status['modal_title']  = 'Tambah Data Terjual';
        $status['modal_size']   = 'modal-lg';
        echo json_encode($status);
    }
    public function edit()
    {
        $id = $this->request->getPost('id');
        $this->data = array('action' => 'update', 'btn' => '<i class="fas fa-edit"></i> Edit');
        foreach ($id as $ids) {
            $get = $this->terjualm->find($ids);
            $data = array(
                'nama' => '<b>' . $get->nama . '</b>',
                'get' => $get,
            );
            $this->data['form_input'][] = view('App\Views\terjual\form_input', $data);
        }
        $status['html']         = view('App\Views\terjual\form_modal', $this->data);
        $status['modal_title']  = 'Update Data Terjual';
        $status['modal_size']   = 'modal-lg';
        echo json_encode($status);
    }
    public function save()
    {
        switch ($this->request->getPost('action')) {
            case 'insert':
                $nama = $this->request->getPost('nama');
                $data = array();
                foreach ($nama as $key => $val) {
                    array_push($data, array(
                        'id_barang' => $this->request->getPost('id_barang')[$key],
                        'jumlah' => $this->request->getPost('jumlah')[$key],
                    ));
                }
                if ($this->terjualm->insertBatch($data)) {
                    $status['type'] = 'success';
                    $status['text'] = 'Data Terjual Tersimpan';
                } else {
                    $status['type'] = 'error';
                    $status['text'] = $this->terjualm->errors();
                }
                echo json_encode($status);
                break;
            case 'update':
                $id = $this->request->getPost('id');
                $data = array();
                foreach ($id as $key => $val) {
                    array_push($data, array(
                        'id' => $val,
                        'id_barang' => $this->request->getPost('id_barang')[$key],
                        'jumlah' => $this->request->getPost('jumlah')[$key],
                    ));
                }
                if ($this->terjualm->updateBatch($data, 'id')) {
                    $status['type'] = 'success';
                    $status['text'] = 'Data Terjual Telah Di Ubah';
                } else {
                    $status['type'] = 'error';
                    $status['text'] = $this->terjualm->errors();
                }
                echo json_encode($status);
                break;
            case 'delete':
                if ($this->terjualm->delete($this->request->getPost('id'))) {
                    $status['type'] = 'success';
                    $status['text'] = '<strong>Deleted..!</strong>Berhasil dihapus';
                } else {
                    $status['type'] = 'error';
                    $status['text'] = '<strong>Oh snap!</strong> Proses hapus data gagal.';
                }
                echo json_encode($status);
                break;
        }
    }
}

/* End of file Terjual.php */
/* Location: ./app/controllers/Terjual.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-12-30 01:38:32 */
/* http://harviacode.com */