<?php

namespace App\Models;

use CodeIgniter\Model;

class TerjualM extends Model
{
    protected $table = 'terjual';
    protected $allowedFields = array('id_barang', 'jumlah');
    protected $returnType     = 'object';
    protected $useSoftDeletes = false;

    protected $useTimestamps = true;
    protected $createdField  = 'created_at';
    protected $updatedField  = 'updated_at';
    protected $deletedField  = 'deleted_at';

    protected $validationRules = [
        'id_barang' => 'required|max_length[11]',
        'jumlah' => 'required|max_length[10]',
    ];

    protected $validationMessages = [
        'id_barang' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal 11 Karakter'],
        'jumlah' => ['required' => 'tidak boleh kosong', 'max_length' => 'Maximal 10 Karakter'],
    ];
}
/* End of file TerjualM.php */
/* Location: ./app/models/TerjualM.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-12-30 01:38:32 */